### ISSUE TITLE
JustBetter\Sentry\Model\SentryLog is a copy of JustBetter\Sentry\Plugin\ExceptionCatcher

### ISSUE THREAD

**Issue by philbernier** [justbetter/magento2-sentry#1]
Hi,

The content in file SentryLog.php is a copy of ExceptionCatcher.php. It seems there was an error during file transfer. Can you please reupload SentryLog.php?

Thank you.

**Comment by rakibabu** [comment]
Hi @philbernier ,

Thanks for reporting this bug. I made an new version 0.0.6 with the correct file.
if you have any other questions, please let me know.

Kind regards,

Rakhal Imming

**Comment by dredumont** [comment]
Can you push the new version on Packagist ?

**Comment by royduin** [comment]
Done: https://packagist.org/packages/justbetter/magento2-sentry
