### ISSUE TITLE
Area code is already set

### ISSUE THREAD

**Issue by andrewsurrey** [justbetter/magento2-sentry#10]
Issues with Magento 2.2.5.

installed via composer

"justbetter/magento2-sentry": "^0.4.1"

Random errors pop up, for example when generating a sitemap, or cache flushed.

'Area code is already set'

stack trace:

#0 Magento\Framework\App\State->setAreaCode() called at [/var/www/html/vendor/justbetter/magento2-sentry/Helper/Data.php:62] #1 JustBetter\Sentry\Helper\Data->__construct() called at [/var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111] #2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [/var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php:108] #3 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [/var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php:70] #4 Magento\Framework\ObjectManager\ObjectManager->get() called at [/var/www/html/generated/code/JustBetter/Sentry/Helper/Data/Proxy.php:84] #5 JustBetter\Sentry\Helper\Data\Proxy->_getSubject() called at [/var/www/html/generated/code/JustBetter/Sentry/Helper/Data/Proxy.php:119] #6 JustBetter\Sentry\Helper\Data\Proxy->isActive() called at [/var/www/html/vendor/justbetter/magento2-sentry/Plugin/MonologPlugin.php:44] #7 JustBetter\Sentry\Plugin\MonologPlugin->addRecord() called at [/var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php:532] #8 Monolog\Logger->debug() called at [/var/www/html/vendor/magento/framework/Cache/InvalidateLogger.php:42] #9 Magento\Framework\Cache\InvalidateLogger->execute() called at [/var/www/html/vendor/magento/framework/Cache/Frontend/Decorator/Logger.php:58] #10 Magento\Framework\Cache\Frontend\Decorator\Logger->log() called at [/var/www/html/vendor/magento/framework/Cache/Frontend/Decorator/Logger.php:48] #11 Magento\Framework\Cache\Frontend\Decorator\Logger->clean() called at [/var/www/html/vendor/magento/module-backend/Controller/Adminhtml/Cache/FlushSystem.php:27] #12 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem->execute() called at [/var/www/html/vendor/magento/framework/App/Action/Action.php:107] #13 Magento\Framework\App\Action\Action->dispatch() called at [/var/www/html/vendor/magento/module-backend/App/AbstractAction.php:229] #14 Magento\Backend\App\AbstractAction->dispatch() called at [/var/www/html/vendor/magento/framework/Interception/Interceptor.php:58] #15 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callParent() called at [/var/www/html/vendor/magento/framework/Interception/Interceptor.php:138] #16 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->Magento\Framework\Interception\{closure}() called at [/var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143] #17 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [/var/www/html/vendor/magento/framework/Interception/Interceptor.php:135] #18 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->Magento\Framework\Interception\{closure}() called at [/var/www/html/vendor/magento/framework/Interception/Interceptor.php:153] #19 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callPlugins() called at [/var/www/html/generated/code/Magento/Backend/Controller/Adminhtml/Cache/FlushSystem/Interceptor.php:26] #20 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->dispatch() called at [/var/www/html/vendor/magento/framework/App/FrontController.php:55] #21 Magento\Framework\App\FrontController->dispatch() called at [/var/www/html/vendor/magento/framework/Interception/Interceptor.php:58] #22 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [/var/www/html/vendor/magento/framework/Interception/Interceptor.php:138] #23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [/var/www/html/vendor/magento/framework/Interception/Interceptor.php:153] #24 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [/var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php:26] #25 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [/var/www/html/vendor/magento/framework/App/Http.php:135] #26 Magento\Framework\App\Http->launch() called at [/var/www/html/vendor/magento/framework/App/Bootstrap.php:256] #27 Magento\Framework\App\Bootstrap->run() called at [/var/www/html/index.php:39]

**Comment by rakibabu** [comment]
Hi @andrewsurrey ,

Thanks for the feedback. This error only occurs when performing backend actions in magento 2?

**Comment by andrewsurrey** [comment]
Hi,

the examples I've seen were mostly backend, but I am pretty sure I have
seen it happen frontend too, but I never took note of that. It was only
specific pages/functionality that created the issue.

flushing cache
genrerate sitemap

those two I specifically recall, others I don't.

thanks

**Comment by rakibabu** [comment]
Ok thanks, I'll try to reproduce this issue on 2.2.5 & 2.2.6 within 2 weeks.

**Comment by kriby** [comment]
@rakibabu , please follow these steps to reproduce issue:
1. php bin/magento setup:upgrade
2. php bin/magento setup:di:compile
3. Reload page on storefront

in my case it is magento 2.2.6 in default mode

**Comment by kyriog** [comment]
I can confirm I had the same problem on my M2.2.6 instance.
Configured in developer mode.

It seems it occurs when we try to reference `\Psr\Log\LoggerInterface` (even in commented code!).

I tried to move to your last commit 4a815b5, and the problem is now gone.

**Comment by kyriog** [comment]
Edit, with your last commit, I can't edit an admin role.

**Comment by awilsonCurt** [comment]
We are also encountering issues with the Area Code error. Updating to the newest version seemed to have no effect.

The error that I encounter happens during install:
php_1_d223d55492b4 | [Progress: 677 / 1358]
php_1_d223d55492b4 | [Progress: 678 / 1358]
php_1_d223d55492b4 | Installing user configuration...
php_1_d223d55492b4 | 
php_1_d223d55492b4 |                                                     
php_1_d223d55492b4 |   [Magento\Framework\Exception\LocalizedException]  
php_1_d223d55492b4 |   Area code is already set  

The error doesn't seem to specifically be coming from the Sentry module, but it only occurs when the Sentry module is a part of the install process.

**Comment by rakibabu** [comment]
Hi All,

Thanks for the feedback. I was able to reproduce this. In version 0.5.0 the setAreaCode is removed and replaced with emulateAreaCode. In addition to that I've found a problem with the CustomerSession which also produced this error. I've proxied that class.

Release 0.5.0 is tested on Magento 2.2.7 & Magento 2.3.0.

Happy to hear your thoughts about this.

**Comment by kriby** [comment]
@rakibabu I updated module to 0.5.0 and the issue is no longer reproducible. Thanks!

**Comment by royduin** [comment]
Thank you for your feedback!
