### ISSUE TITLE
Ability to set Raven options

### ISSUE THREAD

**Issue by ctadlock** [justbetter/magento2-sentry#11]
The url that is sent to sentry is incorrect in our setup. Our Apache web server is running on port 30000, in our AWS ELB we forward ports 80 and 443 to 30000 (for load balancing and SSL offload). When an exception occurs, the correct domain is sent, but it is including the internal port.

Magento: 2.2.6
"justbetter/magento2-sentry": "0.4.2"

![image](https://user-images.githubusercontent.com/1539397/48643804-955b7d00-e995-11e8-8f7c-19afdafbfc62.png)

**Comment by ctadlock** [comment]
There is a Raven option `ignore_server_port` which should be used to handle this. How can we pass through options into raven with this extension?

**Comment by rakibabu** [comment]
Hi @ctadlock ,

I've added in the constructor the parameter ignore_server_port. Can you check if this resolves your issue?
