### ISSUE TITLE
polyfill.io is compromised

### ISSUE THREAD

**Issue by barryvdh** [justbetter/magento2-sentry#139]
See https://github.com/polyfillpolyfill/polyfill-service/issues/2873 and https://polykill.io/

Please remove the CDN asap.

**Comment by indykoning** [comment]
Thank you!
It has been released in version 3.7.0 🚀

**Comment by rommelfreddy** [comment]
why do you not removed it @indykoning ?
The Promise-Polyfill would be only required für IE Browsers. 
Magento does not supports IE Browsers anymore. 
So i would get rid of it.
