### ISSUE TITLE
Setup:DI:Compile Incompatible argument type

### ISSUE THREAD

**Issue by kkrieger85** [justbetter/magento2-sentry#15]
Interception cache generation... 6/7 [========================>---]  85% 29 secs 290.0 MiB 

Errors during compilation:
	Magestore\Bannerslider\Model\ResourceModel\Banner\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Magento\Framework\Model\ResourceModel\Db\AbstractDb; File:
[PWD]/vendor/magestore/module-bannerslider/Model/ResourceModel/Banner/Collection.php

Total Errors Count: 1

  [Magento\Framework\Validator\Exception]
  Error during compilation

===========

I tried to install it to Magento 2.2.3

**Comment by ameerElsherif** [comment]
How did you solve this?
