### ISSUE TITLE
bin/magento setup:upgrade print message say area did not set 

### ISSUE THREAD

**Issue by nmcit-helal** [justbetter/magento2-sentry#17]
in terminal when  using bin/magento setup:upgrade printed message say area did not set  and when disable the plug-in magneto 2.2 works fine

**Comment by rakibabu** [comment]
Hi @nmcit-helal,

Thanks for the report.
Can you specify which version of Magento 2.2 you work?


Thanks in advance.

**Comment by nmcit-helal** [comment]
Hi @rakibabu,
i am using magneto 2.2.2 
Thanks,

**Comment by shochdoerfer** [comment]
Having the same issue in a project with Magento version 2.2.5 & justbetter/magento2-sentry in version 0.6.1.

**Comment by rakibabu** [comment]
Hi @shochdoerfer & @nmcit-helal ,

Thanks for responding with this issue. Unfortunately I can't reproduce this issue on a clean install with magento. Can you specify your steps yo reproduce this on you Magento 2 versions? By the way you guys should update to Magento 2.2.8, there are some security issue with Magento lower than 2.2.8. 

I'm closing this issue for now, please feel free to submit an issue with the proper steps to reproduce and with the latest incremental version of magento.

Regards,

Rakhal
