### ISSUE TITLE
Use referenceBlock instead of referenceContainer

### ISSUE THREAD

**Issue by qdb** [justbetter/magento2-sentry#18]
Hi,

I think in [view/frontend/layout/default.xml](https://github.com/justbetter/magento2-sentry/blob/master/view/frontend/layout/default.xml#L4) you need to use referenceBlock instead of referenceContainer. I upgraded the plugin to newest version today in my project and had issues with existing code because of that. 

Please check similar issue: https://github.com/magento/magento2/issues/16497

Thanks for all the work you make on this plugin. Really appreciate it.

Regards,
Adam.

**Comment by rakibabu** [comment]
Hi @qdb ,

Thanks for notifying me :). This has been changed in version 0.6.2.

Regards,

Rakhal
