### ISSUE TITLE
Add user info to error log when user is logged in

### ISSUE THREAD

**Issue by dareenzo** [justbetter/magento2-sentry#20]
**Do you want to request a *feature* or report a *bug*?**

request feature

**Feature: What is your use case for such a feature?**

I need to know with whom the error happened such that I can be able to proactively contact the user and request more info or let them know they should update the app somehow.

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

When the user is logged in use `Raven.setUser()` and include the logged in user details there

**What is the version of Magento and of Sentry extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.3.1
Magento2Sentry 0.7.2

**Comment by rakibabu** [comment]
Hi @dareenzo ,

Thanks for the feature request, i'll implement this tomorrow. In release 0.9.0.

**Comment by peterjaap** [comment]
@rakibabu any sight on when 0.9.0 will be released? `develop` right now is equal to `0.8.0` so I'm not sure what is in 0.9.0?
