### ISSUE TITLE
Upgrade to Sentry API v2 + exception handling?

### ISSUE THREAD

**Issue by JosephMaxwell** [justbetter/magento2-sentry#25]
**Feature: What is your use case for such a feature?**
I am comparing Rollbar vs Sentry and am seeing that Rollbar (while very basic) has good root-level exception handling. This is quite important, and seems to be missing from Sentry (just log publishing).

However, the v2 of the Sentry API has much better exception handling.

Are you open to pull requests? Or, are you already working on such an implementation? 

I am using the Magento 2.3.2 with the latest version of this module.

**Comment by rakibabu** [comment]
Hi @JosephMaxwell ,

I was planning to rework the module with v2 of sentry, however I can't find the time right now to upgrade the module with the extension. If you want to make a start with this i'll really appreciate it.

We should collaborate on the rework to version 2 :)

**Comment by JosephMaxwell** [comment]
Hello @rakibabu ,

Thanks for the response. The module looks pretty simple overall. Are there any special callouts that are important to you? My goal, otherwise, is to catch as many logs/exceptions as possible and push up to sentry.

Joseph

**Comment by JosephMaxwell** [comment]
@rakibabu,

Hi there. Here is my pull request: https://github.com/justbetter/magento2-sentry/pull/26

As soon as you can merge/tag it, I would be grateful as I hope to deploy this on a number of our other projects.

Joseph

**Comment by Niko9911** [comment]
@rakibabu Please.... We are still waiting for this.

**Comment by rakibabu** [comment]
@Niko9911 @JosephMaxwell ,

The PR's are merged and will be released today.

Thanks for contributing and for you patience.

Raki
