### ISSUE TITLE
Admin system configuration slowdown when saving config value

### ISSUE THREAD

**Issue by DominicWatts** [justbetter/magento2-sentry#28]
Magento 2.3.2 vanilla using luma theme.  Very few customisations.

I noticed today on a dev install as soon as sentry extension is enabled when you click save in system configuration you experience slowdown 

I've done a bit of profiling and it's not MySQL.  MySQL sleep processes stack up whilst waiting on the application.

php-fpm appears to be hanging on something.  But I can't pinpoint it to anything particular. New relic simply indicates an increase in response time

It's the difference between a 5 - 10 second save and a 20 - 30 second save

Of course this could be expected behaviour

**Comment by JeroenBoersma** [comment]
Me too, I've done my Blackfire profiling and it's a deadlock.

`Cache->flush` will rebuilt the cache which locks the cache until it's written and it also writes something to the log..

The log where Sentry gets injected wants to check if Sentry is enabled in config, so it triggers a `cache->load` which is of coarse locked, which results in a deadlock.

I would suggest, having that Sentry is a `debug` tool that we'll move to `environment` variables via `app/etc/env.php`

Another solution would be to built a `configuration` object during bootstrap events in Magento which will be used the rest of that code execution.

**Comment by rakibabu** [comment]
The PR is merged, thanks for contributing to this issue.
