### ISSUE TITLE
Ability to send test event

### ISSUE THREAD

**Issue by ctadlock** [justbetter/magento2-sentry#3]
Would be good to have a button to send a test event to Sentry to make sure its all working correctly. Often extensions like SMTP email have this and its very useful.

**Comment by royduin** [comment]
Thanks for the suggestion, we'll implement it next week and keep you posted.

**Comment by rakibabu** [comment]
Hi @ctadlock ,

In the new version 0.1.0 I've added a button to send a test event to sentry based on your domain field. The test event is triggered from the /vendor/bin directory.

Kind regards,

Rakhal Imming
