### ISSUE TITLE
Implement PHPCSFixer

### ISSUE THREAD

**Issue by NikoGrano** [justbetter/magento2-sentry#31]
To keep codestyling same everywhere, we should utilize PHPCSFixer which will perform automatically fixes into code style. Example configuration will be posted via PR.

**Comment by rakibabu** [comment]
@Niko9911 ,

Thanks for contributing!

**Comment by Niko9911** [comment]
@rakibabu ?? Wtf

**Comment by royduin** [comment]
Indeed, wtf... reopend 👍

**Comment by DominicWatts** [comment]
Check output of github actions - I think these could be handled manually

**Comment by Niko9911** [comment]
Github actions should only do check and reject faulty code styling BEFORE merging master. Cs fixing itself should be done in level of composer

**Comment by DominicWatts** [comment]
I disagree.  Automated code checks should be advisory and not preventative.  But their results are not always beneficial.  Plus standards change.

Although I understand your reasoning.  I work in a team and frequently have to clean up code.

**Comment by Niko9911** [comment]
This is the reason why we cannot have nice things 🙃

**Comment by indykoning** [comment]
Hi, 
do you mean a pre-commit hook or something simmilar?
It is a good suggestion but since we already check code style in the repository this isn't high on the to-do list.
PRs are more than welcome 😄

**Comment by NikoGrano** [comment]
If requested I can provide PR with Magento Codestyling. I will not force it pre-commit or anything. It can be there and if required it can be set lint the codestyle on CI.

**Comment by indykoning** [comment]
We now have styleCI running to cover codestyle.
Plus as of recently PHPStan to catch potential bugs before they happen 🚀
