### ISSUE TITLE
Ability to set Magento modes that send errors to Sentry

### ISSUE THREAD

**Issue by ctadlock** [justbetter/magento2-sentry#4]
Currently errors are only sent to Sentry if Magento is in `production` mode. That's great for when the site is running, but not helpful during development. There should be an admin setting to allow for errors to be sent for any/all Magento modes.

**Comment by ctadlock** [comment]
In addition, the current Magento mode should be sent over to Sentry su that any filtering can happen there.

**Comment by rakibabu** [comment]
Hi @ctadlock ,

Thanks for the suggestion, I'll implement this enhancement soon.

Kind regards,

Rakhal Imming

**Comment by ctadlock** [comment]
I tried out your latest code for sending a test event. Im getting this error when your admin config page loads. 

![image](https://user-images.githubusercontent.com/1539397/39388325-01d13d00-4a34-11e8-9045-85909f2a621d.png)

**Comment by ctadlock** [comment]
^ static content is not deployed on this site because its in development; which is the whole purpose of this feature.

**Comment by rakibabu** [comment]
Hi @ctadlock ,

I've added an option in de latest code to fix your issue with testing this module on development mode. There's an option in the backend `Send errors in development mode` which you can turn on to test this module.

Static content is not required to deploy `testsentry.js`. Please ensure you've the option `Allow Symlinks` turned on in your magento 2 installation when on development mode.

Please let me know if the module works as expected.

Kind regards,

Rakhal Imming
