### ISSUE TITLE
Update Javascript SDK to latest version

### ISSUE THREAD

**Issue by peterjaap** [justbetter/magento2-sentry#41]
https://github.com/justbetter/magento2-sentry/blob/master/view/frontend/templates/script/sentry.phtml#L11

We're now at 4.5.3 while 5.91 is the most recent version. See changelog here; https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md

**Comment by peterjaap** [comment]
As far as I can see we're only using basic functionality and only doing a `Sentry.init()` so upgrading shouldn't break stuff.

**Comment by peterjaap** [comment]
Actually, we upgraded from 5.9.1 to 5.10.0 locally and it broke several things in our custom React components. So beware.

**Comment by peterjaap** [comment]
Might be that 5.10.1 fixed that. Will report back after testing.

**Comment by rakibabu** [comment]
@peterjaap ,

Nice catch. I'd love to hear if it works.

**Comment by peterjaap** [comment]
@woutersteen could you try this out? I now see 5.10.2 is released as well.

**Comment by alexbejan-mavfarm** [comment]
Do you guys know why if the extension is not updated, the sentry notifications don't work any more

**Comment by indykoning** [comment]
Hi @alexbejan-mavfarm,
What version of this module are you running?
In https://github.com/justbetter/magento2-sentry/commit/b713b3e5158cd465ab0da4b76c68ca5427fd0aae
(Available in the latest version)
the js sdk version has been bumped from `4.5.3` to `5.17.0`

Maybe Sentry does not support 4.5.3 anymore.

**Comment by alexbejan-mavfarm** [comment]
@indykoning I was using `2.2.3` and the sentry notifications stopped working for critical log entries. Once I updated to `2.3.0` they started to work again. This has also happened last time the module (and presumably the sdk) were updated.

**Comment by indykoning** [comment]
That is quite odd indeed.
Can you find any errors in your logs?
Older versions of this module should keep working as long as it is supported by the Magento version.

Changes to this repository should not influence the module you have locally.
Are you sure nothing else happened around the same time, like a Magento update or changes of sentry settings?

**Comment by alexbejan-mavfarm** [comment]
There were no errors or changes. I think the SDK version increased and I assume sentry is holding the notifications if they don't come from the latest sdk version. I'll keep an eye next time this happens and reply.

**Comment by indykoning** [comment]
Sounds good to me!
Since i don't think this is closely enough related to this issue and if it happens again it deserves it's own issue, i'll close this issue.
If it happens again please open a new issue and provide all the information you can give 😃

**Comment by indykoning** [comment]
The SDK version has been updated to 5.17.0 in release [2.3.0](https://github.com/justbetter/magento2-sentry/releases/tag/2.3.0) 😄
