### ISSUE TITLE
Script Tag placement

### ISSUE THREAD

**Issue by matthiashamacher** [justbetter/magento2-sentry#45]
It's just a question regarding the script tag placement.
Why is there the opportunity to choose where to initialise the script tag?

As it is defined in the Sentry Docs I think it would be better to just implement it in the header. "You should init the Sentry Browser SDK as soon as possible during your page load" (https://docs.sentry.io/platforms/javascript/#configure-the-sdk)

**Comment by royduin** [comment]
Maybe @michielgerritsen can answer that for you because he created it here: https://github.com/justbetter/magento2-sentry/pull/13

**Comment by michielgerritsen** [comment]
Yes, the best is to put in the header as it will catch more errors, but sooner or later you will hit a "SEO expert" requiring you to move it to the footer.

**Comment by indykoning** [comment]
I think this question has been answered, so i'll be closing this issue.
If you don't think so feel free to reopen it 😃
