### ISSUE TITLE
Script tag included regardless of admin configuration for enabling it

### ISSUE THREAD

**Issue by adamj88** [justbetter/magento2-sentry#47]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**Bug: What is the current behavior?**

Script tag is included when admin configuration "Enable Sentry script tag" is set to 'No'

**Bug: What is the expected behavior?**

Script tag respects admin config

**Bug: What is the proposed solution?**

Update Helper/Data.php to correctly use admin configuration.

**What is the version of Magento and of Sentry extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.3.3 and Justbetter Sentry v2.2.1

** More Detail **

Believe it was this change which introduced it: https://github.com/justbetter/magento2-sentry/commit/1f60b01e798f548cc518e97c787e70f9d7e28a29#diff-735f70c1f948ebbd90915b1548d93432R161

**Comment by indykoning** [comment]
The PR with the fix has been merged and is available to update with composer.
