### ISSUE TITLE
Doesn't seem to work with earlier versions of magento2?

### ISSUE THREAD

**Issue by zack6849** [justbetter/magento2-sentry#5]
I'm on magento 2.1.10 and can't build without commenting out the following line from the di.xml

https://github.com/justbetter/magento2-sentry/blob/master/etc/di.xml#L7

Is there anything that doesn't work from this being disabled i'm not noticing?
It still sends test events and exceptions.
I should also mention that it wouldnt even install via composer install because it wanted a newer version of monolog.

**Comment by zack6849** [comment]
Thanks a ton, like i said it seems functional for barebones functionality just by forcing the install and commenting out that line

**Comment by rakibabu** [comment]
@zack6849 ,

With build you mean running `setup:di:compile`? With a clean install of magento 2.1.10 I can build the module with no errors. Can you provide me with more information about this? 
For composer installation with version 2.1.10 I'll downgrade the version of monolog to version 1.16.

Happy to hear from you.

Kind regards,

Rakhal Imming

**Comment by rakibabu** [comment]
@zack6849 ,

Please check if version 0.2.1 is working for you on Magento 2.1.10 and via composer.

Happy to hear from you.

Kind regards,

Rakhal Imming

**Comment by zack6849** [comment]
Hi,
0.2.1 isn't availible on composer yet, do you want to push it so I can test?

**Comment by rakibabu** [comment]
Hi @zack6849 ,

Please install via composer version 0.2.2. Something weird happend with version 0.2.1. I cannot reproduce your error with Magento 2.1.10 & monolog 1.16. Did you deleted the generation folder and cleared the cache? 

Happy to hear from you.

**Comment by rakibabu** [comment]
Hi @zack6849 ,

Thanks for the debug report, i've tested above with all functions regarding the removal of the line in the di.xml. All functions works fine in Magento 2.1.x and Magento 2.2.x. 

Can you test it one more time in your build? When everything works as expected i'll release the new version.

Kind regards,

Rakhal Imming

**Comment by zack6849** [comment]
Well, it sent events and whatnot, but you added that line, no? 

What was the reason that line was here?

**Comment by andrewsurrey** [comment]
was this solved?
I had this working perviously, done a fresh build with 2.1.* and getting this error.

**Comment by zack6849** [comment]
Hi Andrew, the dev never got back to me, but if you look higher in the comments you can remove the line specified manually and it will work. 

Specifically, this line: https://github.com/justbetter/magento2-sentry/blob/master/etc/di.xml#L7

**Comment by royduin** [comment]
Sorry guys, I'll ask @rakibabu to look into this shortly.

**Comment by rakibabu** [comment]
Hi Guys,

I release 0.3.0 for the support for magento 2.1.x. 
@zack6849 the rule in de di.xml is the injection of the monolog ravenhandler for the handler in de SentryLog model. The rule is not necessary since I construct a new Ravenhandler in the method sendRecordToSentry.
