### ISSUE TITLE
System Config throws JS Errors

### ISSUE THREAD

**Issue by DavidLambauer** [justbetter/magento2-sentry#51]
Hi, 

I am using the latest version of this module on Magento 2.3.4 Commerce. I am not able to send sentry test events via the button that is provided in the System Configuration.

The following error occurs:

![image](https://user-images.githubusercontent.com/1841317/76526206-7972c900-646d-11ea-8ebb-17030def15eb.png)

You'll be able to reproduce this issue by navigating to the System Config of this module.

**Comment by indykoning** [comment]
Hi,

We are unable to reproduce this on any of our environments (running 2.3.4 CE)
Might your static content not yet be compiled, please check if the file exists in `pub/static/adminhtml/Magento/backend/en_US/JustBetter_Sentry/js/testsentry.js`
Replace `en_US` with your back-end language.

If it does not exist make sure to run 
`bin/magento setup:static-content:deploy en_US --theme Magento/backend`

After which it should not 404 any more.

Please let me know if this worked 😃

**Comment by DavidLambauer** [comment]
Alright, works now. Seemed to be a caching thing 🙈
