### ISSUE TITLE
Add LogRocket integration

### ISSUE THREAD

**Issue by peterjaap** [justbetter/magento2-sentry#52]
It would be great to have LogRocket integration in the extension, see https://blog.logrocket.com/extending-sentry-with-logrocket-52e2f5b67d5a/

Two bits of code should be added;

Right after <head>:

```
<script src="https://cdn.lr-ingest.io/LogRocket.min.js" crossorigin="anonymous"></script>
<script>window.LogRocket && window.LogRocket.init('INITKEY_HERE');</script>
```

Before </body>:

```
LogRocket.getSessionURL(sessionURL => {
  Sentry.configureScope(scope => {
    scope.setExtra("sessionURL", sessionURL);
  });
});
```

We'll need to add two configuration opties; Enable/disable LogRocket integration, and an input field for the LogRocket init key (which you'll get when you create a project in LogRocket).

**Comment by peterjaap** [comment]
Extra bonus feature; identify logged-in users;

> Use `LogRocket.identify` to distinguish and describe your users. This will allow you to search for specific user sessions by name, email and id. It will make a major difference in your happiness!

```
// This is an example script - don't forget to change it!
LogRocket.identify('THE_USER_ID_IN_YOUR_APP', {
  name: 'James Morrison',
  email: 'jamesmorrison@example.com',

  // Add your own custom user variables here, ie:
  subscriptionType: 'pro'
});
```

[Reference](https://docs.logrocket.com/reference#identify)

**Comment by pimruiter** [comment]
Hi Peter Jaap,

Thanks for the requested feature! Looks like a nice addition to the Sentry extension. This will be part of the next update, which will be within the next few weeks.

**Comment by indykoning** [comment]
Hi Peter Jaap,

This feature is now available in the latest ([2.3.0](https://github.com/justbetter/magento2-sentry/releases/tag/2.3.0)) release!
Thank you for the suggestion! 😄

**Comment by peterjaap** [comment]
@indykoning that is seriously fast, thanks!!

**Comment by oneserv-heuser** [comment]
@indykoning Just stumbled upon this nice feature and tried to make it work in the adminhtml scope, but it doesn't seem to work. After going through the code in the PR it looks like as it is not supported. Would it be possbile to add support for js error tracking with sentry and logrocket in the adminhtml scope (with user tracking)? That would be really nice!
