### ISSUE TITLE
Sentry Domain not filled! error

### ISSUE THREAD

**Issue by shuat** [justbetter/magento2-sentry#53]
version 2.2.3
magento/product-community-edition 2.3.4
I followed all the install instructions and added the following to env.php 
```
    'sentry' => [
        'dsn' => 'https://45127da1d5534ba2a1e6e83875dc861b@o406150.ingest.sentry.io/5273034',
        'environment' => 'production',
        'log_level' => \Monolog\Logger::WARNING,
        'mage_mode_development' => false,
    ]
```
I went to Stores > Configuration > JustBetter > Sentry and turned on and tried testing and got the error message `Sentry Domain not filled!` 

What should I do to debug further?

**Comment by shuat** [comment]
Putting this here is case anyone else gets stuck and someone should come up with better messaging.

This message means that 
$this->helperSentry->isActive() is not active
see [this](https://github.com/justbetter/magento2-sentry/blob/master/Helper/Data.php#L126) and [this](https://github.com/justbetter/magento2-sentry/blob/master/Controller/Adminhtml/Test/Sentry.php#L97)

The messaging should be a little better.

This is caused by the fact that my current mode is not production the way around without setting to production is to set `'mage_mode_development' => true,`

**Comment by pimruiter** [comment]
Hi Shuat,

Thanks for the suggestion. We will improve the message in the current 2.2.4 update we're currently working on, so that the improvement wil be in the upcomming release.

 Thanks again.

**Comment by indykoning** [comment]
Hi Shuat,

The [release with better error messages](https://github.com/justbetter/magento2-sentry/releases/tag/2.3.0) when configuration is missing, or there is a problem is now live!
Thank you for your feedback 😄
