### ISSUE TITLE
insanity logging levels

### ISSUE THREAD

**Issue by andrewsurrey** [justbetter/magento2-sentry#6]
Default logging level is absolute insanity, and sould probably be removed altogether.

This caused our sentry account to hit it's quota of events within a few page loads. Sending thousands of log entries per page load into a system meant to exception logging is crazy.

**Comment by rakibabu** [comment]
I @andrewsurrey ,

You're absolutely right, this is crazy. I removed this line and the default log level when installing in now info.

Kind regards,

Rakhal Imming
