### ISSUE TITLE
Javascript error missing environment variable

### ISSUE THREAD

**Issue by webtekindo** [justbetter/magento2-sentry#61]
In Sentry with PHP errors we have the correct value in **enviroment** tag. But for Javascript errors, the **environment** tag is not there. It makes it difficult to trace them in our different enviroments.

Do you have a solution to it?

**Comment by matthiashamacher** [comment]
@webtekindo 
I can confirm the issue and created a Pull Request to add the environment to JavaScript implementation.

**Comment by indykoning** [comment]
I've merged and released the PR in [2.3.2](https://github.com/justbetter/magento2-sentry/releases/tag/2.3.2)

Thank you @matthiashamacher for your contribution 🎉 

It should be out soon, if there are problems on 2.3.2 feel free to open a new issue 🚀
