### ISSUE TITLE
<unlabeled event> - Discarded invalid value for parameter 'sentry.interfaces.Message' 

### ISSUE THREAD

**Issue by venturestream** [justbetter/magento2-sentry#7]
Getting lots of empty exceptions through
<unlabeled event>

Discarded invalid value for parameter 'sentry.interfaces.Message' 

value:

{
formatted: {}, 
message: {}, 
params: []
}
latest version, running on Magento 2.1

**Comment by rakibabu** [comment]
Hi @venturestream can you provide me with more data to reproduce this issue? 

Happy to hear from you.

**Comment by rakibabu** [comment]
Hi @venturestream ,

I've updated the extension to get more info in sentry. Refactored some code, can you update the extension and check if the message is still there?

Kind regards,

Rakhal Imming
