### ISSUE TITLE
Not in production and development mode is false.

### ISSUE THREAD

**Issue by nguyentrunghieu98** [justbetter/magento2-sentry#70]
'sentry' => [
        'dsn' => 'https://627aac5b01a344898ec4a85b9.......',
        'logrocket_key' => 'magento-2-test/magento',
        'environment' => 'developer',
        'log_level' => \Monolog\Logger::WARNING,
        'mage_mode_development' => false
    ]

I got this error when testing sentry

**Comment by matthiashamacher** [comment]
@nguyentrunghieu98 
You get the error because your Magento is not in production mode and Sentry is disabled for developer mode. Either change to production mode `bin/magento deploy:mode:set production` or set the `mage_mode_development` to true in your configuration.

**Comment by nguyentrunghieu98** [comment]
Can the Magento 2.4.1 version use the sentry module?

**Comment by nguyentrunghieu98** [comment]
![Uploading Screenshot.png…]()

**Comment by indykoning** [comment]
Yes, it supports and has been tested on 2.4.1 😃
