### ISSUE TITLE
Compatibility with Magento Cloud

### ISSUE THREAD

**Issue by scolandrea** [justbetter/magento2-sentry#80]
Hey guys!

I really like this extension I would love to use it on Magento cloud projects but I found a big blocker. You are using `DeploymentConfig` to get all the configuration sentry settings. The problem with that is you are recollecting these options either from env.php or config.php. For on-premise projects is not a big issue to add all the settings into the env.php file but for Magento Cloud projects isn't possible.

Magento Cloud recommends using environment variables to override settings like `CONFIG__DEFAULT__SENTRY__DSN` which in this case is not an option because the extension is using **Magento Deployment Configuration**.

I just forked your project and I would love to propose one of two solutions. 

- Treat the settings as module configuration.
- Change the approach and accept environment variables as well.

What do you think?

**Comment by julioxx22** [comment]
It would be a good approach for Magento Cloud

**Comment by indykoning** [comment]
I think treating the settings as module configuration would be the best approach to this because why would we read the environment variables manually when a more flexible solution already exists 😉 

I would prefer the deployment config to still be allowed for backwards compatibility 🙂

**Comment by ArjenMiedema** [comment]
Has anyone made a solution on how to enable Sentry on Adobe Commerce Cloud? I'd really like to implement this in a project.

I can see if I can implement the logic to make it available in the module configuration, but I don't want to re-invent the wheel here.

**Comment by indykoning** [comment]
This has been added in https://github.com/justbetter/magento2-sentry/releases/tag/3.5.0 🚀
