### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by peterjaap** [justbetter/magento2-sentry#84]
After install this extension on Magento 2.4.4 with PHP 8.1 (with `--ignore-platform-reqs` composer flag), I'm getting this error when running `bin/magento setup:upgrade`;

```
PHP Fatal error:  Declaration of JustBetter\Sentry\Plugin\MonologPlugin::addRecord($level, $message, array $context = []) must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = []): bool in /data/client/magento2/vendor/justbetter/magento2-sentry/Plugin/MonologPlugin.php on line 54
```

**Comment by indykoning** [comment]
Support for the newer php version with the newer monolog versions is now released as version 3.0.0 🎉 
Let me know if you run into any more issues on Magento 2.4.4 😁
