### ISSUE TITLE
Incompatible with monolog/monolog v2.7.0

### ISSUE THREAD

**Issue by adamj88** [justbetter/magento2-sentry#93]
Today, monolog/monolog was updated to v2.7.0 where they added an additional `$datetime` parameter to the `addRecord` method in: https://github.com/Seldaek/monolog/releases/tag/2.7.0

Since this module requires >=2.0.0 of monolog an error is produced:

```
Warning: Declaration of JustBetter\Sentry\Plugin\MonologPlugin::addRecord(int $level, string $message, array $context = Array): bool should be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = Array, ?Monolog\DateTimeImmutable $datetime = NULL): bool in vendor/justbetter/magento2-sentry/Plugin/MonologPlugin.php on line 54
```

Ref:

- https://github.com/justbetter/magento2-sentry/blob/d4ae32882a39e127a863a2c74b7f62ec4341c1b4/Plugin/MonologPlugin.php#L54
- https://github.com/Seldaek/monolog/blob/2.7.0/src/Monolog/Logger.php#L312

**Comment by indykoning** [comment]
This has now been fixed and released as version 3.1.0 🚀
